BEGIN;

INSERT INTO category_small VALUES (1, 'Electric Materials', 1);
INSERT INTO category_small VALUES (2, 'Instant Foods', 2);
INSERT INTO category_small VALUES (3, 'Cooking Materials', 1);
INSERT INTO category_small VALUES (4, 'Decorative', 1);
INSERT INTO category_small VALUES (5, 'Cosmetics', 1);
INSERT INTO category_small VALUES (6, 'Stationery', 1);
INSERT INTO category_small VALUES (7, 'Cooling Materials', 1);
INSERT INTO category_small VALUES (8, 'Party Materials', 1);
INSERT INTO category_small VALUES (9, 'Fashion', 4);
INSERT INTO category_small VALUES (10, 'Shoes', 4);
INSERT INTO category_small VALUES (11, 'Gardening', 1);
INSERT INTO category_small VALUES (12, 'Bath', 1);
INSERT INTO category_small VALUES (13, 'Storage', 3);
INSERT INTO category_small VALUES (14, 'Bicycle', 1);
INSERT INTO category_small VALUES (15, 'Outdoor', 1);

COMMIT;

BEGIN;

INSERT INTO category_large VALUES (1, 'Sundries');
INSERT INTO category_large VALUES (2, 'Foods');
INSERT INTO category_large VALUES (3, 'Furniture');
INSERT INTO category_large VALUES (4, 'Clothes');

COMMIT;

BEGIN;

INSERT INTO product_master VALUES (1, 'Dry Cells (AA size)', 100, 1);
INSERT INTO product_master VALUES (2, 'Dry Cells (AAA size)', 100, 1);
INSERT INTO product_master VALUES (3, 'Dry Cells (C size)', 150, 1);
INSERT INTO product_master VALUES (4, 'Instant noodle in cup (Soy Sauce)', 140, 2);
INSERT INTO product_master VALUES (5, 'Instant noodle in cup (Salty)', 140, 2);
INSERT INTO product_master VALUES (6, 'Instant noodle in cup (Chili Tomato)', 140, 2);
INSERT INTO product_master VALUES (7, 'Instant noodle in cup (Curry)', 140, 2);
INSERT INTO product_master VALUES (8, 'Instant noodle in cup (Cheese in Curry)', 140, 2);
INSERT INTO product_master VALUES (9, 'Instant noodle in cup (Seafood)', 140, 2);
INSERT INTO product_master VALUES (10, 'Instant noodle in cup (Basil and Chicken)', 140, 2);
INSERT INTO product_master VALUES (11, 'Picture Frame (A4 size)', 398, 4);
INSERT INTO product_master VALUES (12, 'Picture Frame (B5 size)', 348, 4);
INSERT INTO product_master VALUES (13, 'Small Box (L)', 1500, 13);
INSERT INTO product_master VALUES (14, 'Small Box (M)', 1000, 13);
INSERT INTO product_master VALUES (15, 'Small Box (S)', 500, 13);
INSERT INTO product_master VALUES (16, 'Pen case', 298, 6);
INSERT INTO product_master VALUES (17, 'Pen case (Cloth)', 398, 6);
INSERT INTO product_master VALUES (18, 'BBQ Gridiron (L)', 498, 3);
INSERT INTO product_master VALUES (19, 'BBQ Gridiron (M)', 448, 3);
INSERT INTO product_master VALUES (20, 'BBQ Gridiron (S)', 398, 3);
INSERT INTO product_master VALUES (21, 'Round Fan', 98, 7);
INSERT INTO product_master VALUES (22, 'Folding Fan', 198, 7);
INSERT INTO product_master VALUES (23, 'Bell for Bicycle', 298, 14);
INSERT INTO product_master VALUES (24, 'Sun-glass', 1300, 9);
INSERT INTO product_master VALUES (25, 'Sandals (L)', 498, 10);
INSERT INTO product_master VALUES (26, 'Sandals (M)', 498, 10);
INSERT INTO product_master VALUES (27, 'Sandals (S)', 498, 10);
INSERT INTO product_master VALUES (28, 'Sandals for Kids', 398, 10);
INSERT INTO product_master VALUES (29, 'Ice Pack', 248, 3);
INSERT INTO product_master VALUES (30, 'Insect repellent incense', 398, 15);
INSERT INTO product_master VALUES (31, 'Boater', 630, 9);
INSERT INTO product_master VALUES (32, 'Straw Hat', 798, 9);
INSERT INTO product_master VALUES (33, 'Straw Hat with Ribbon', 1000, 9);
INSERT INTO product_master VALUES (34, 'Sunblock', 398, 15);
INSERT INTO product_master VALUES (35, 'Sun Screen', 1780, 11);
INSERT INTO product_master VALUES (36, 'Wind-bell', 398, 7);
INSERT INTO product_master VALUES (37, 'Chop sticks 100 pieces', 100, 3);
INSERT INTO product_master VALUES (38, 'Plastic Straw 100 pieces', 100, 3);
INSERT INTO product_master VALUES (39, 'Notebook lined A-type', 198, 6);
INSERT INTO product_master VALUES (40, 'Notebook lined B-type', 198, 6);
INSERT INTO product_master VALUES (41, 'Plastic Eraser', 98, 6);
INSERT INTO product_master VALUES (42, 'Pencil HB', 100, 6);
INSERT INTO product_master VALUES (43, 'Pencil B', 100, 6);
INSERT INTO product_master VALUES (44, 'Pencil 2B', 100, 6);
INSERT INTO product_master VALUES (45, 'Pencil 3B', 100, 6);
INSERT INTO product_master VALUES (46, 'Pencil 4B', 100, 6);
INSERT INTO product_master VALUES (47, 'Pencil H', 100, 6);
INSERT INTO product_master VALUES (48, 'Pencil 2H', 100, 6);
INSERT INTO product_master VALUES (49, 'Pencil 3H', 100, 6);
INSERT INTO product_master VALUES (50, 'Pencil 4H', 100, 6);
INSERT INTO product_master VALUES (51, 'Spare Lead for Automatic Pencil HB', 100 ,6);
INSERT INTO product_master VALUES (52, 'Spare Lead for Automatic Pencil B', 100 ,6);
INSERT INTO product_master VALUES (53, 'Spare Lead for Automatic Pencil 2B', 100, 6);
INSERT INTO product_master VALUES (54, 'Spare Lead for Automatic Pencil H', 100 ,6);
INSERT INTO product_master VALUES (55, 'Spare Lead for Automatic Pencil 2H', 100, 6);
INSERT INTO product_master VALUES (56, 'Colored Pencil Black', 100, 6);
INSERT INTO product_master VALUES (57, 'Colored Pencil White', 100, 6);
INSERT INTO product_master VALUES (58, 'Colored Pencil Red', 100, 6);
INSERT INTO product_master VALUES (59, 'Colored Pencil Orange', 100, 6);
INSERT INTO product_master VALUES (60, 'Colored Pencil Yellow', 100, 6);
INSERT INTO product_master VALUES (61, 'Colored Pencil Green', 100 ,6);
INSERT INTO product_master VALUES (62, 'Colored Pencil Blue', 100, 6);
INSERT INTO product_master VALUES (63, 'Colored Pencil Purple', 120, 6);
INSERT INTO product_master VALUES (64, 'Colored Pencil Cyan', 120, 6);
INSERT INTO product_master VALUES (65, 'Colored Pencil Magenta', 130, 6);
INSERT INTO product_master VALUES (66, 'Colored Pencil Indigo', 120, 6);
INSERT INTO product_master VALUES (67, 'Tablet Stand', 500, 1);
INSERT INTO product_master VALUES (68, 'Thumbtacks 100 pieces', 250, 6);
INSERT INTO product_master VALUES (69, 'Magnetsheet 1m x 1m', 100 ,6);
INSERT INTO product_master VALUES (70, 'Magnetsheet 50cm x 50cm', 70 ,6);
INSERT INTO product_master VALUES (71, 'Hangers 10 pieces', 300, 9);
INSERT INTO product_master VALUES (72, 'Pail for bath (Large)', 398, 12);
INSERT INTO product_master VALUES (73, 'Pail for bath (Small)', 298, 12);
INSERT INTO product_master VALUES (74, 'Bucket', 198, 11);
INSERT INTO product_master VALUES (75, 'Wartering Pot', 298, 11);
INSERT INTO product_master VALUES (76, 'Vinyl Hose 1m', 198, 11);
INSERT INTO product_master VALUES (77, 'Vinyl Hose 3m', 398, 11);
INSERT INTO product_master VALUES (78, 'Vinyl Hose 5m', 598, 11);
INSERT INTO product_master VALUES (79, 'Flowerpot (S)', 240, 11);
INSERT INTO product_master VALUES (80, 'Flowerpot (M)', 360, 11);
INSERT INTO product_master VALUES (81, 'Flowerpot (L)', 480, 11);
INSERT INTO product_master VALUES (82, 'Imitation Flower (Sunflower)', 150, 4);
INSERT INTO product_master VALUES (83, 'Imitation Flower (Lily)', 120, 4);
INSERT INTO product_master VALUES (84, 'Imitation Flower (Cosmos)', 130, 4);
INSERT INTO product_master VALUES (85, 'Imitation Flower (Lavender)', 100, 4);
INSERT INTO product_master VALUES (86, 'Perfume', 398, 5);
INSERT INTO product_master VALUES (87, 'Lipstick', 198, 5);
INSERT INTO product_master VALUES (88, 'Foundation Cream', 600, 5);
INSERT INTO product_master VALUES (89, 'Powder Puff', 250, 5);
INSERT INTO product_master VALUES (90, 'Ethernet Cable 1m', 398, 1);
INSERT INTO product_master VALUES (91, 'Power Strip', 148, 1);
INSERT INTO product_master VALUES (92, 'Power Cable Extension', 198, 1);
INSERT INTO product_master VALUES (93, 'Glowstick Blue', 200, 8);
INSERT INTO product_master VALUES (94, 'Glowstick Yellow', 200, 8);
INSERT INTO product_master VALUES (95, 'Glowstick Pink', 200, 8);
INSERT INTO product_master VALUES (96, 'Glowstick Orange', 400, 8);
INSERT INTO product_master VALUES (97, 'Glowstick Green', 200, 8);
INSERT INTO product_master VALUES (98, 'Glowstick White', 300, 8);
INSERT INTO product_master VALUES (99, 'Glowstick Red', 200, 8);
INSERT INTO product_master VALUES (100, 'Glowstick Vaiolet', 200, 8);


COMMIT;
