BEGIN;

INSERT INTO product_master VALUES (1, 'Dry Cells (AA size)');
INSERT INTO product_master VALUES (2, 'Dry Cells (AAA size)');
INSERT INTO product_master VALUES (3, 'Dry Cells (C size)');
INSERT INTO product_master VALUES (4, 'Instant noodle in cup (Soy Sauce)');
INSERT INTO product_master VALUES (5, 'Instant noodle in cup (Salty)');
INSERT INTO product_master VALUES (6, 'Instant noodle in cup (Chili Tomato)');
INSERT INTO product_master VALUES (7, 'Instant noodle in cup (Curry)');
INSERT INTO product_master VALUES (8, 'Instant noodle in cup (Cheese in Curry)');
INSERT INTO product_master VALUES (9, 'Instant noodle in cup (Seafood)');
INSERT INTO product_master VALUES (10, 'Instant noodle in cup (Basil and Chicken)');
INSERT INTO product_master VALUES (11, 'Picture Frame (A4 size)');
INSERT INTO product_master VALUES (12, 'Picture Frame (B5 size)');
INSERT INTO product_master VALUES (13, 'Small Box (L)');
INSERT INTO product_master VALUES (14, 'Small Box (M)');
INSERT INTO product_master VALUES (15, 'Small Box (S)');
INSERT INTO product_master VALUES (16, 'Pen case');
INSERT INTO product_master VALUES (17, 'Pen case (Cloth)');
INSERT INTO product_master VALUES (18, 'BBQ Gridiron (L)');
INSERT INTO product_master VALUES (19, 'BBQ Gridiron (M)');
INSERT INTO product_master VALUES (20, 'BBQ Gridiron (S)');
INSERT INTO product_master VALUES (21, 'Round Fan');
INSERT INTO product_master VALUES (22, 'Folding Fan');
INSERT INTO product_master VALUES (23, 'Wind Bell');
INSERT INTO product_master VALUES (24, 'Sun-glass');
INSERT INTO product_master VALUES (25, 'Sandals (L)');
INSERT INTO product_master VALUES (26, 'Sandals (M)');
INSERT INTO product_master VALUES (27, 'Sandals (S)');
INSERT INTO product_master VALUES (28, 'Sandals for Kids');
INSERT INTO product_master VALUES (29, 'Ice Pack');
INSERT INTO product_master VALUES (30, 'Insect repellent incense');
INSERT INTO product_master VALUES (31, 'Boater');
INSERT INTO product_master VALUES (32, 'Straw Hat');
INSERT INTO product_master VALUES (33, 'Straw Hat with Ribbon');
INSERT INTO product_master VALUES (34, 'Sunblock');
INSERT INTO product_master VALUES (35, 'Sun Screen');
INSERT INTO product_master VALUES (36, 'Wind-bell');
INSERT INTO product_master VALUES (37, 'Chop sticks 100 pieces');
INSERT INTO product_master VALUES (38, 'Plastic Straw 100 pieces');
INSERT INTO product_master VALUES (39, 'Notebook lined A-type');
INSERT INTO product_master VALUES (40, 'Notebook lined B-type');
INSERT INTO product_master VALUES (41, 'Plastic Eraser');
INSERT INTO product_master VALUES (42, 'Pencil HB');
INSERT INTO product_master VALUES (43, 'Pencil B');
INSERT INTO product_master VALUES (44, 'Pencil 2B');
INSERT INTO product_master VALUES (45, 'Pencil 3B');
INSERT INTO product_master VALUES (46, 'Pencil 4B');
INSERT INTO product_master VALUES (47, 'Pencil H');
INSERT INTO product_master VALUES (48, 'Pencil 2H');
INSERT INTO product_master VALUES (49, 'Pencil 3H');
INSERT INTO product_master VALUES (50, 'Pencil 4H');
INSERT INTO product_master VALUES (51, 'Spare Lead for Automatic Pencil HB');
INSERT INTO product_master VALUES (52, 'Spare Lead for Automatic Pencil B');
INSERT INTO product_master VALUES (53, 'Spare Lead for Automatic Pencil 2B');
INSERT INTO product_master VALUES (54, 'Spare Lead for Automatic Pencil H');
INSERT INTO product_master VALUES (55, 'Spare Lead for Automatic Pencil 2H');
INSERT INTO product_master VALUES (56, 'Colored Pencil Black');
INSERT INTO product_master VALUES (57, 'Colored Pencil White');
INSERT INTO product_master VALUES (58, 'Colored Pencil Red');
INSERT INTO product_master VALUES (59, 'Colored Pencil Orange');
INSERT INTO product_master VALUES (60, 'Colored Pencil Yellow');
INSERT INTO product_master VALUES (61, 'Colored Pencil Green');
INSERT INTO product_master VALUES (62, 'Colored Pencil Blue');
INSERT INTO product_master VALUES (63, 'Colored Pencil Purple');
INSERT INTO product_master VALUES (64, 'Colored Pencil Cyan');
INSERT INTO product_master VALUES (65, 'Colored Pencil Magenta');
INSERT INTO product_master VALUES (66, 'Colored Pencil Indigo');
INSERT INTO product_master VALUES (67, 'Tablet Stand');
INSERT INTO product_master VALUES (68, 'Thumbtacks 100 pieces');
INSERT INTO product_master VALUES (69, 'Magnetsheet 1m x 1m');
INSERT INTO product_master VALUES (70, 'Magnetsheet 50cm x 50cm');
INSERT INTO product_master VALUES (71, 'Hangers 10 pieces');
INSERT INTO product_master VALUES (72, 'Pail for bath (Large)');
INSERT INTO product_master VALUES (73, 'Pail for bath (Small)');
INSERT INTO product_master VALUES (74, 'Bucket');
INSERT INTO product_master VALUES (75, 'Wartering Pot');
INSERT INTO product_master VALUES (76, 'Vinyl Hose 1m');
INSERT INTO product_master VALUES (77, 'Vinyl Hose 3m');
INSERT INTO product_master VALUES (78, 'Vinyl Hose 5m');
INSERT INTO product_master VALUES (79, 'Flowerpot (S)');
INSERT INTO product_master VALUES (80, 'Flowerpot (M)');
INSERT INTO product_master VALUES (81, 'Flowerpot (L)');
INSERT INTO product_master VALUES (82, 'Imitation Flower (Sunflower)');
INSERT INTO product_master VALUES (83, 'Imitation Flower (Lily)');
INSERT INTO product_master VALUES (84, 'Imitation Flower (Cosmos)');
INSERT INTO product_master VALUES (85, 'Imitation Flower (Lavender)');
INSERT INTO product_master VALUES (86, 'Perfume');
INSERT INTO product_master VALUES (87, 'Lipstick');
INSERT INTO product_master VALUES (88, 'Foundation Cream');
INSERT INTO product_master VALUES (89, 'Powder Puff');
INSERT INTO product_master VALUES (90, 'Ethernet Cable 1m');
INSERT INTO product_master VALUES (91, 'Power Strip');
INSERT INTO product_master VALUES (92, 'Power Cable Extension');
INSERT INTO product_master VALUES (93, 'Glowstick Blue');
INSERT INTO product_master VALUES (94, 'Glowstick Yellow');
INSERT INTO product_master VALUES (95, 'Glowstick Pink');
INSERT INTO product_master VALUES (96, 'Glowstick Orange');
INSERT INTO product_master VALUES (97, 'Glowstick Green');
INSERT INTO product_master VALUES (98, 'Glowstick White');
INSERT INTO product_master VALUES (99, 'Glowstick Red');
INSERT INTO product_master VALUES (100, 'Glowstick Vaiolet');


COMMIT;

